restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
# local-cores: 1
# use at most N cores of the host
# machine in parallel (default: number of CPU cores of 
